/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package editTasks;

import entity.Controls;
import entity.Student;
import entity.Subjects;
import entity.Tasks;
import java.sql.Date;
import java.util.ArrayList;
import java.util.List;
import javax.swing.RowSorter;
import javax.swing.SortOrder;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import menu.menu_headman;
import services.ControlsService;
import services.SubjectsService;
import services.TasksService;

/**
 *
 * @author 79105
 */
public class EditTableFrameTasks extends javax.swing.JFrame {

    private List<Tasks> list;
    private ModelTasks tasksmodel = new ModelTasks();
    private menu_headman parent;
    private Student student;

    public EditTableFrameTasks(menu_headman p, List<Tasks> l, Student s) {
        initComponents();
        this.setLocationRelativeTo(p);
        this.list = l;
        this.parent = p;
        this.student = s;

        for (Tasks t : list) {
            if (t.getGroups().getGroupName().equals(student.getGroup().getGroupName())) {
                if ("Вся группа".equals(student.getTeam().getTeam())) {
                    tasksmodel.appendElem(t);
                } else if ((t.getTeams().getTeam().equals(student.getTeam().getTeam())) || ("Вся группа".equals(t.getTeams().getTeam()))) {
                    tasksmodel.appendElem(t);
                }
            }

        }
        
        
        jTable1.setModel(tasksmodel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ЗАДАНИЯ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Назад");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Редактировать");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 258, Short.MAX_VALUE)
                                .addComponent(jButton2)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(4, 4, 4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // back

        this.setVisible(false);
        parent.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // edit

        int row = jTable1.getSelectedRow();

        Date deadline = Date.valueOf(jTable1.getModel().getValueAt(row, 0).toString());

        String subject = jTable1.getModel().getValueAt(row, 1).toString();
        String control = jTable1.getModel().getValueAt(row, 2).toString();
        String desc = jTable1.getModel().getValueAt(row, 3).toString();

        SubjectsService s = new SubjectsService();
        Subjects subj = s.findByName(subject);

        ControlsService c = new ControlsService();
        Controls cont = c.findByName(control);

        Tasks selTask = new Tasks(cont, subj, deadline, desc, student.getGroup(), student.getTeam());
        this.setVisible(false);
        new EditTask(this, selTask).setVisible(true);


    }//GEN-LAST:event_jButton2ActionPerformed

    public void repaint_table() {
        ModelTasks newmodel = new ModelTasks();

        List<Tasks> l = new TasksService().findAll();

        for (Tasks t : l) {
            if (t.getGroups().getGroupName().equals(student.getGroup().getGroupName())) {
                if ("Вся группа".equals(student.getTeam().getTeam())) {
                    newmodel.appendElem(t);
                } else if ((t.getTeams().getTeam().equals(student.getTeam().getTeam())) || ("Вся группа".equals(t.getTeams().getTeam()))) {
                    newmodel.appendElem(t);
                }
            }

        }
        
        
        
        jTable1.setModel(newmodel);
        
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
