package entity;
// Generated 23 ���. 2021 �., 15:01:38 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Auditoriums generated by hbm2java
 */
@Entity
@Table(name = "auditoriums",
        schema = "public"
)
public class Auditoriums implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "auditorium_id", unique = true, nullable = false)
    private int auditoriumId;

    @Column(name = "auditorium", nullable = false)
    private String auditorium;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "auditoriums")
    private Set<TimetableIate> timetableIates = new HashSet(0);

    public Auditoriums() {
    }

    public Auditoriums(int auditoriumId, String auditorium) {
        this.auditoriumId = auditoriumId;
        this.auditorium = auditorium;
    }

    public Auditoriums(int auditoriumId, String auditorium, Set<TimetableIate> timetableIates) {
        this.auditoriumId = auditoriumId;
        this.auditorium = auditorium;
        this.timetableIates = timetableIates;
    }

    public int getAuditoriumId() {
        return this.auditoriumId;
    }

    public void setAuditoriumId(int auditoriumId) {
        this.auditoriumId = auditoriumId;
    }

    public String getAuditorium() {
        return this.auditorium;
    }

    public void setAuditorium(String auditorium) {
        this.auditorium = auditorium;
    }

    public Set<TimetableIate> getTimetableIates() {
        return this.timetableIates;
    }

    public void setTimetableIates(Set<TimetableIate> timetableIates) {
        this.timetableIates = timetableIates;
    }

}