package entity;
// Generated 23 ���. 2021 �., 15:01:38 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Controls generated by hbm2java
 */
@Entity
@Table(name = "controls",
        schema = "public"
)
public class Controls implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "control_id", unique = true, nullable = false)
    private int controlId;

    @Column(name = "control", nullable = false)
    private String control;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "controls")
    private Set<Tasks> taskses = new HashSet(0);

    public Controls() {
    }

    public Controls(int controlId, String control) {
        this.controlId = controlId;
        this.control = control;
    }

    public Controls(int controlId, String control, Set<Tasks> taskses) {
        this.controlId = controlId;
        this.control = control;
        this.taskses = taskses;
    }

    public int getControlId() {
        return this.controlId;
    }

    public void setControlId(int controlId) {
        this.controlId = controlId;
    }

    public String getControl() {
        return this.control;
    }

    public void setControl(String control) {
        this.control = control;
    }

    public Set<Tasks> getTaskses() {
        return this.taskses;
    }

    public void setTaskses(Set<Tasks> taskses) {
        this.taskses = taskses;
    }

}



