package entity;
// Generated 23 ���. 2021 �., 15:01:38 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Parity generated by hbm2java
 */
@Entity
@Table(name = "parity",
        schema = "public"
)
public class Parity implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "parity_id", unique = true, nullable = false)
    private int parityId;

    @Column(name = "week", nullable = false)
    private String week;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "parity")
    private Set<TimetableIate> timetableIates = new HashSet(0);

    public Parity() {
    }

    public Parity(int parityId, String week) {
        this.parityId = parityId;
        this.week = week;
    }

    public Parity(int parityId, String week, Set<TimetableIate> timetableIates) {
        this.parityId = parityId;
        this.week = week;
        this.timetableIates = timetableIates;
    }

    public int getParityId() {
        return this.parityId;
    }

    public void setParityId(int parityId) {
        this.parityId = parityId;
    }

    public String getWeek() {
        return this.week;
    }

    public void setWeek(String week) {
        this.week = week;
    }

    public Set<TimetableIate> getTimetableIates() {
        return this.timetableIates;
    }

    public void setTimetableIates(Set<TimetableIate> timetableIates) {
        this.timetableIates = timetableIates;
    }

}



