package entity;
// Generated 23 ���. 2021 �., 15:01:38 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Periods generated by hbm2java
 */
@Entity
@Table(name = "periods",
        schema = "public"
)
public class Periods implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "period_id", unique = true, nullable = false)
    private int periodId;

    @Column(name = "period_num", nullable = false)
    private int periodNum;

    @Temporal(TemporalType.TIME)
    @Column(name = "begining", nullable = false, length = 15)
    private Date begining;

    @Temporal(TemporalType.TIME)
    @Column(name = "ending", nullable = false, length = 15)
    private Date ending;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "periods")
    private Set<TimetableIate> timetableIates = new HashSet(0);

    public Periods() {
    }

    public Periods(int periodId, int periodNum, Date begining, Date ending) {
        this.periodId = periodId;
        this.periodNum = periodNum;
        this.begining = begining;
        this.ending = ending;
    }

    public Periods(int periodId, int periodNum, Date begining, Date ending, Set<TimetableIate> timetableIates) {
        this.periodId = periodId;
        this.periodNum = periodNum;
        this.begining = begining;
        this.ending = ending;
        this.timetableIates = timetableIates;
    }

    public int getPeriodId() {
        return this.periodId;
    }

    public void setPeriodId(int periodId) {
        this.periodId = periodId;
    }

    public int getPeriodNum() {
        return this.periodNum;
    }

    public void setPeriodNum(int periodNum) {
        this.periodNum = periodNum;
    }

    public Date getBegining() {
        return this.begining;
    }

    public void setBegining(Date begining) {
        this.begining = begining;
    }

    public Date getEnding() {
        return this.ending;
    }

    public void setEnding(Date ending) {
        this.ending = ending;
    }

    public Set<TimetableIate> getTimetableIates() {
        return this.timetableIates;
    }

    public void setTimetableIates(Set<TimetableIate> timetableIates) {
        this.timetableIates = timetableIates;
    }

}


