package entity;
// Generated 23 ���. 2021 �., 15:01:38 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Teachers generated by hbm2java
 */
@Entity
@Table(name = "teachers",
        schema = "public"
)
public class Teachers implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "teacher_id", unique = true, nullable = false)
    private int teacherId;

    @Column(name = "teacher_fio", nullable = false)
    private String teacherFio;

    @Column(name = "email")
    private String email;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "teachers")
    private Set<TimetableIate> timetableIates = new HashSet(0);

    public Teachers() {
    }

    public Teachers(int teacherId, String teacherFio, String teacherEmail) {
        this.teacherId = teacherId;
        this.teacherFio = teacherFio;
        this.email = teacherEmail;
    }
    
    public Teachers(String teacherFio, String teacherEmail) {
        this.teacherFio = teacherFio;
        this.email = teacherEmail;
    }

    public Teachers(int teacherId, String teacherFio, String email, Set<TimetableIate> timetableIates) {
        this.teacherId = teacherId;
        this.teacherFio = teacherFio;
        this.email = email;
        this.timetableIates = timetableIates;
    }

    public int getTeacherId() {
        return this.teacherId;
    }

    public void setTeacherId(int teacherId) {
        this.teacherId = teacherId;
    }

    public String getTeacherFio() {
        return this.teacherFio;
    }

    public void setTeacherFio(String teacherFio) {
        this.teacherFio = teacherFio;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public Set<TimetableIate> getTimetableIates() {
        return this.timetableIates;
    }

    public void setTimetableIates(Set<TimetableIate> timetableIates) {
        this.timetableIates = timetableIates;
    }
    
  

}