package entity;
// Generated 23 ���. 2021 �., 15:01:38 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Teams generated by hbm2java
 */
@Entity
@Table(name = "teams",
        schema = "public"
)
public class Teams implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "team_id", unique = true, nullable = false)
    private int teamId;

    @Column(name = "team", nullable = false)
    private String team;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "teams")
    private Set<TimetableIate> timetableIates = new HashSet(0);
    
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "teams")
    private Set<Tasks> tasks = new HashSet(0);

    public Teams() {
    }

    public Teams(int teamId, String team) {
        this.teamId = teamId;
        this.team = team;
    }

    public Teams(int teamId, String team, Set<TimetableIate> timetableIates, Set<Tasks> task) {
        this.teamId = teamId;
        this.team = team;
        this.timetableIates = timetableIates;
        this.tasks = task;
    }

    public int getTeamId() {
        return this.teamId;
    }

    public void setTeamId(int teamId) {
        this.teamId = teamId;
    }

    public String getTeam() {
        return this.team;
    }

    public void setTeam(String team) {
        this.team = team;
    }

    public Set<TimetableIate> getTimetableIates() {
        return this.timetableIates;
    }

    public void setTimetableIates(Set<TimetableIate> timetableIates) {
        this.timetableIates = timetableIates;
    }

    public Set<Tasks> getTasks() {
        return tasks;
    }

    public void setTasks(Set<Tasks> tasks) {
        this.tasks = tasks;
    }
    
    

}
