package entity;
// Generated 23 ���. 2021 �., 15:01:38 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Weekdays generated by hbm2java
 */
@Entity
@Table(name = "weekdays",
        schema = "public"
)
public class Weekdays implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "weekday_id", unique = true, nullable = false)
    private int weekdayId;

    @Column(name = "weekday", nullable = false)
    private String weekday;

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "weekdays")
    private Set<TimetableIate> timetableIates = new HashSet(0);

    public Weekdays() {
    }

    public Weekdays(int weekdayId, String weekday) {
        this.weekdayId = weekdayId;
        this.weekday = weekday;
    }

    public Weekdays(int weekdayId, String weekday, Set<TimetableIate> timetableIates) {
        this.weekdayId = weekdayId;
        this.weekday = weekday;
        this.timetableIates = timetableIates;
    }

    public int getWeekdayId() {
        return this.weekdayId;
    }

    public void setWeekdayId(int weekdayId) {
        this.weekdayId = weekdayId;
    }

    public String getWeekday() {
        return this.weekday;
    }

    public void setWeekday(String weekday) {
        this.weekday = weekday;
    }

    public Set<TimetableIate> getTimetableIates() {
        return this.timetableIates;
    }

    public void setTimetableIates(Set<TimetableIate> timetableIates) {
        this.timetableIates = timetableIates;
    }

}
